[package]
name = "wordshk_tools"
version = "0.1.0"
edition = "2018"

[dependencies]
lip = "5.1.1"
csv = "1.1"
lazy_static = "1.4.0"
indoc = "1.0"
unicode-segmentation = "1.8.0"
unicode_names2 = "0.4.0"
serde = "1.0"
serde_json = "1.0"
