[package]
name = "test_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wordshk_tools = "3.15.5"
serde_json = "1.0"
itertools = "0.10.5"
