[package]
name = "export_api"
version = "0.1.0"
edition = "2021"

[dependencies]
wordshk_tools = { path = "../../" }
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
