[package]
name = "export_sqlite_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wordshk_tools = { path = "../../" }
rusqlite = "0.31.0"
